********** 31/01/2019 11.34.53 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
Source: Test of Logging 2
Stack Trace: 
********** 31/01/2019 11.35.52 **********
Exception Type: System.Exception
Exception: Exception of type 'System.Exception' was thrown.
Source: Test of Logging 3
Stack Trace: 
********** 04/30/2019 10:04:30 **********
Inner Exception Type: System.IO.IOException
Inner Exception: Unable to read data from the transport connection: Operation canceled.
Inner Source: System.Net.Sockets
Inner Stack Trace: 
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Exception Type: System.Threading.Tasks.TaskCanceledException
Exception: The operation was canceled.
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 04/30/2019 15:41:14 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 04/30/2019 15:41:29 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 05/01/2019 19:22:57 **********
Inner Exception Type: System.IO.IOException
Inner Exception: The server returned an invalid or unrecognized response.
Inner Source: System.Net.Http
Inner Stack Trace: 
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: An error occurred while sending the request.
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 05/01/2019 19:27:08 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 05/01/2019 19:30:05 **********
Inner Exception Type: System.IO.IOException
Inner Exception: Unable to read data from the transport connection: Operation canceled.
Inner Source: System.Net.Sockets
Inner Stack Trace: 
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Exception Type: System.Threading.Tasks.TaskCanceledException
Exception: The operation was canceled.
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 05/01/2019 19:32:02 **********
Inner Exception Type: System.IO.IOException
Inner Exception: The server returned an invalid or unrecognized response.
Inner Source: System.Net.Http
Inner Stack Trace: 
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: An error occurred while sending the request.
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 05/01/2019 19:32:12 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 05/13/2019 17:07:44 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 06/03/2019 09:16:33 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 06/26/2019 00:14:32 **********
Inner Exception Type: System.IO.IOException
Inner Exception: The server returned an invalid or unrecognized response.
Inner Source: System.Net.Http
Inner Stack Trace: 
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: An error occurred while sending the request.
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 06/26/2019 00:21:50 **********
Inner Exception Type: System.IO.IOException
Inner Exception: Unable to read data from the transport connection: Operation canceled.
Inner Source: System.Net.Sockets
Inner Stack Trace: 
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Exception Type: System.Threading.Tasks.TaskCanceledException
Exception: The operation was canceled.
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 07/21/2019 16:01:51 **********
Inner Exception Type: System.IO.IOException
Inner Exception: Unable to read data from the transport connection: Operation canceled.
Inner Source: System.Net.Sockets
Inner Stack Trace: 
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Exception Type: System.Threading.Tasks.TaskCanceledException
Exception: The operation was canceled.
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 07/21/2019 16:32:45 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 07/21/2019 16:47:31 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 07/21/2019 17:02:56 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

********** 07/21/2019 17:03:01 **********
Inner Exception Type: System.Net.Sockets.SocketException
Inner Exception: Connection refused
Inner Source: System.Private.CoreLib
Inner Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
Exception Type: System.Net.Http.HttpRequestException
Exception: Connection refused
Source: Base DataServices, PostAsync<T>
Stack Trace: 
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at LogisticsBooking.FrontEnd.DataServices.BaseDataService.GetAsync(String baseurl) in /Users/casperhasnsen/Documents/Projects/LogisticBooking/LogisticsBooking.FrontEnd/LogisticsBooking.FrontEnd/DataServices/BaseDataService.cs:line 148

